config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'results', to: 'pages#results'
  resources :suppliers, only: [ :index, :show, :new, :create ] do
    resources :orders, only: [ :index, :show, :new, :create, :update ], type: "order"
    resources :templates, only: [ :index, :new, :create, :edit, :update ], controller: :orders, type: "template"
    resources :products, only: [ :new, :create ]
  end

  # get 'templates', to: "orders#index", type: "template"
  # resources :templates, only: %i[index new create edit update destroy], type: "template"

  resources :templates, controller: :orders, type: "template"

  resources :orders, only: [:index, :new, :show, :create, :update ], type: "order"
  resources :products, only: %i[index show update]
  resources :inventories, only: [:index, :show, :update] do
    collection do
      get :sync
    end
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <i class="fa-solid fa-bars"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<div class="container">
  <div id="mySidenav" class="sidenav">
      <%= link_to 'Home', root_path %>
      <% if user_signed_in? %>
      <%= link_to 'Suppliers', suppliers_path %>
      <%= link_to 'Templates', templates_path %>
      <%= link_to 'Orders', orders_path %>
      <%= link_to 'Inventory', inventories_path %>
      <%= button_to "Logout", destroy_user_session_path, {method: :delete, class: "btn-logout btn btn-outline-dark"} %>

      <% else %>
      <div class="accordion accordion-flush" id="accordionFlushExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="flush-headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
              Why Srimble?
            </button>
          </h2>
          <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><img src="https://img.icons8.com/office/40/000000/overview-pages-2.png"/>Overview </li>
                <li class="list-group-item"><img src="https://img.icons8.com/ultraviolet/40/000000/concept.png"/>Solution</li>
                <li class="list-group-item"><img src="https://img.icons8.com/external-indigo-line-kalash/48/000000/external-features-business-management-indigo-line-kalash.png"/>Features</li>
                <li class="list-group-item"><img src="https://img.icons8.com/ultraviolet/40/000000/groups.png"/>About us</li>

              </ul>
            </div>
          </div>
        </div>
      </div>
        <%= link_to "Log In", new_user_session_path, class: "btn-login btn btn-outline-dark" unless user_signed_in? %>
        <%= link_to "Get Started", new_user_registration_path, class: "btn-signup btn btn-primary" unless user_signed_in? %>

      <% end %>
  </div>

</div>

<div class="menu-and-back">
  <%= link_to image_tag("srimble_logo.png"), root_path, class: "link-logo" %>
  <div class="searchbar"><%= render "shared/searchbar3" %></div>
  <span class="menu-btn" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; </span>
  <a href="javascript:void(0)" class="closebtn visually-hidden" onclick="closeNav()">&#x2715;</a>
</div>

<br>
<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "100%";
  document.querySelector(".closebtn").classList.toggle("visually-hidden");
  document.querySelector(".menu-btn").classList.toggle("visually-hidden");
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
  document.querySelector(".closebtn").classList.toggle("visually-hidden");
  document.querySelector(".menu-btn").classList.toggle("visually-hidden");
}
</script>

app/views/shared/_searchbar.html.erb
<div class="search">
  <%= form_with url: results_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Search by supplier, delivery date etc..",
      aria: { label: "Recipient's username", describedby: "button-addon2" } %>
    <%= button_tag type: 'submit', class: "search-btn", id: "button-addon2" do %>
        <i class="fa-solid fa-magnifying-glass" aria-hidden="true"></i>
    <% end %>
  <% end %>
</div>

app/views/shared/_searchbar2.html.erb
<div class="search-box">
  <button class="btn-search s-body"><i class="fas fa-search"></i></button>
  <div class="input-search s-body">
    <%= form_with url: results_path, method: :get, class: "s-body ss-box" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "ss-box",
        placeholder: "Search by supplier, delivery date etc..",
        aria: { label: "Recipient's username", describedby: "button-addon2" } %>
    <% end %>
  </div>
</div>

app/views/shared/_searchbar3.html.erb
<div class="container">

  <div class="search-bar">


      <%= form_with url: results_path, method: :get do %>
        <% text_field_tag :query,
          params[:query],
          class: "search-bar__input",
          # placeholder: "Enter your search here..",
          aria: { label: "General search box" },
          html: { class: "search-bar__input" } %>
      <% end %>

    <i class="fas fa-search" style="color: black"></i>
    <%# <button class="search-bar__submit">
    </button> %>

  </div>

</div>