config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'results', to: 'pages#results'
  resources :suppliers, only: [ :index, :show, :new, :create ] do
    resources :orders, only: [ :index, :show, :new, :create, :update ], type: "order"
    resources :templates, only: [ :index, :new, :create, :edit, :update ], controller: :orders, type: "template"
    resources :products, only: [ :new, :create ]
  end

  # get 'templates', to: "orders#index", type: "template"
  # resources :templates, only: %i[index new create edit update destroy], type: "template"

  resources :templates, controller: :orders, type: "template"

  resources :orders, only: [:index, :new, :show, :create, :update ], type: "order"
  resources :products, only: %i[index show update]
  resources :inventories, only: [:index, :show, :update] do
    collection do
      get :sync
    end
  end

end

app/views/pages/_landing_page.html.erb
  <div class="col p-0">
    <div class="card banner pt-5">
      <div class="card-body">
        <h1 class="card-title display-3">more time on the food <br> <small class="text-muted">less time on the phone</small> </h1>
        <p class="card-text">Make your orders over-easy. Manage day-to-day operations with Srimble: suppliers, orders, products and stock all in one place.</p>
        <%= link_to "Get Started", new_user_registration_path, class: "btn-signup btn btn-primary" unless user_signed_in? %>
      </div>
        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
        <lottie-player src="https://assets10.lottiefiles.com/packages/lf20_pfwovzsz.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;" hover loop  autoplay></lottie-player>
    </div>
  </div>
  <div class="row" style="margin-left: 1px;">
    <h1 class="feature-header display-3">an intuitive tool to empower your team</h1>
    <div class="col-sm-12 col-md-6">
      <div class="card feature-card suppliers">
        <div class="row">
          <div class="col">
            <img src="https://img.icons8.com/clouds/100/null/shop.png" class="card-img-top"/>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <h2 class="card-title">Suppliers</h2>
            <p class="card-text">Keep all your suppliers organised; all their products and your orders with them all stored safely with us so you won't have to. </p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-md-6">
      <div class="card feature-card orders">
        <div class="row">
          <div class="col">
            <img src="https://img.icons8.com/clouds/100/null/invoice.png" class="card-img-top"/>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <h2 class="card-title">Orders</h2>
            <p class="card-text">Get an order out in seconds with our templates tools, without ever needing to triple-check for typos, or calculating minimum order quantities. </p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-md-6">
      <div class="card feature-card inventory">
        <div class="row">
          <div class="col">
            <img src="https://img.icons8.com/clouds/100/null/grocery-shelf.png" class="card-img-top"/>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <h2 class="card-title">Inventory</h2>
            <p class="card-text">Stock-taking simplified: Srimble populates your inventory when it comes, and alerts you when an item is too low, so you'll never 86 a crowd favorite. </p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-md-6">
      <div class="card feature-card square">
        <div class="row">
          <div class="col">
            <img src="https://img.icons8.com/clouds/100/null/handshake.png" class="card-img-top"/>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <h2 class="card-title">API Intergration</h2>
            <p class="card-text">Srimble allows for Square Point-Of-Sales (POS) intergration so that inventory gets updated anytime u want, and complete control of your sales and purchases in different locations.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row footer" style="margin-left: 1px;">
    <div class="col">
      <%= image_tag "srimble_logo.png", class: "logo" %>
      <%= link_to "About", "#" %>
      <%= link_to "Product", "#" %>
      <%= link_to "Team", "#" %>
      <%= link_to " Contact Us", "#" %>
      <ul>
        <li><i class="fa-brands fa-twitter"></i></li>
        <li><i class="fa-brands fa-instagram"></i></li>
        <li><i class="fa-brands fa-github"></i></li>
      </ul>
    </div>
  </div>

app/views/pages/_orders_list.html.erb
<div class="orders">
  <div class="list-group">
      <% current_user.orders.where(delivery_date: Date.today..DateTime::Infinity.new).order(:delivery_date).first(10).each do |order| %>
        <div class="notif-card mb-2">
        <%#= link_to order_path(order), class: "notif-card mb-2" do %>
          <small>Arriving <%= order.delivery_date == Date.today ? "today" : order.delivery_date %></small>
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1 text-truncate"><%= "Order ##{order.id} -" %><%= order.supplier.name %></h5>
            <span class="material-symbols-outlined">arrow_forward_ios</span>
          </div>

          <div class="btn-tray">
            <%# Order details %>
            <div class="order-btn">
              <%= link_to order do %>
                <i class="fa-solid fa-file"></i>
              <% end %>
            </div>

            <%# delivered button %>
            <div class="col-12">
              <%= simple_form_for(order) do |f| %>
                <%= f.hidden_field :status, :value => "delivered" %>
                <%= f.submit '✅', class: "fa-solid fa-square-check", data: {turbo_confirm: "All items were delivered for this order?"} do %>
                  <i class=""></i>
                <% end %>
              <% end %>
            </div>

          </div>
        <%# end %>
        </div>
      <% end %>
  </div>
</div>

app/views/pages/_products_list.html.erb
<div class="products">
  <% current_user.inventories.running_low.order(:quantity_bal).first(10).each do |inventory| %>
    <div class="notif-card-product mb-2">
      <%# <%= link_to new_order_path( template: template ), class: "notif-card2 mb-2 templates" do %>
      <small>Sold by <%= inventory.product.supplier.name %><br/></small>
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1 text-truncate"><%= inventory.product.name %></h5>
        <a class="view-btn-extra-small"><%= inventory.quantity_bal %></a>
      </div>
      <span style="color: red; font-weight: bold;"> - <%= (inventory.quantity_bal - inventory.par_bal).abs() %> vs min</span><br/>

      <div class="btn-tray-product">
        <%# Create new order with supplier %>
        <div class="order-btn">
          <%= link_to new_supplier_order_path(inventory.product.supplier) do %>
            <i class="fa-solid fa-arrow-up-right-from-square"></i>
          <% end %>
        </div>

        <%# go to product/show %>
        <div class="order-btn">
          <%= link_to product_path(inventory.product) do %>
            <i class="fa-solid fa-eye"></i>
          <% end %>
        </div>

      </div>
    </div>
  <% end %>
</div>

app/views/pages/_templates_list.html.erb
<div class="templates">
  <% current_user.templates.order(:created_at).first(10).each do |template| %>
    <div class="notif-card-template mb-2">
      <%# <%= link_to new_order_path( template: template ), class: "notif-card2 mb-2 templates" do %>
      <small><%= template.supplier.name %><br/></small>
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1 text-truncate"><%= template.name %></h5>
        <span class="material-symbols-outlined">arrow_forward_ios</span>
      </div>
      <%# <% end %>
    <%# </div> %>

      <div class="btn-tray-template">
        <%# Create new order with template %>
        <div class="order-btn">
          <%= link_to new_order_path(template: template) do %>
            <i class="fa-solid fa-cart-plus"></i>
          <% end %>
        </div>

        <%# edit template button %>
        <div class="order-btn">
          <%= link_to edit_template_path(template) do %>
            <i class="fa-solid fa-pen-to-square"></i>
          <% end %>
        </div>

      </div>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <% if user_signed_in? %>
    <h2>Hello Christina,</h2>
    <h3 style="margin-bottom: 30px;">what would you like to do today?</h3>
    <div class="row mb-4 dash-icons">
      <div class="col">
        <%= link_to new_supplier_order_path(Supplier.find(1)) do %>
        <%= image_tag "https://img.icons8.com/ios/50/null/create-order--v1.png", class: "quick-link-btn" %>
        <% end %>
        <br><small>New Order</small>
      </div>
      <div class="col">
        <%= link_to suppliers_path do %>
        <%= image_tag "https://img.icons8.com/ios/50/null/supplier.png", class: "quick-link-btn" %>
        <% end %>
      <br><small>Suppliers</small>
      </div>
      <div class="col">
        <%= link_to orders_path(status: "pending") do %>
        <%= image_tag "https://img.icons8.com/ios/50/null/data-pending.png", class: "quick-link-btn" %>
        <% end %>
        <br><small>Pending Orders</small>
      </div>
      <div class="col">
        <%= link_to sync_inventories_path do %>
        <%= image_tag "https://img.icons8.com/ios/50/null/cloud-sync--v1.png", class: "quick-link-btn" %>
        <% end %>
        <br><small>Sync from POS</small>
      </div>
    </div>

        <div class="tab">
          <button class="tablinks" onclick="openList(event, 'Orders')" id="defaultOpen">Orders</button>
          <button class="tablinks" onclick="openList(event, 'Templates')">Templates</button>
          <button class="tablinks" onclick="openList(event, 'Low')">Running Low</button>
        </div>
      <div class="col-sm-6 col-md-6 content">
        <!-- Tab links -->

        <!-- Tab content -->
        <div id="Orders" class="tabcontent" style="border: none">
          <%= render "orders_list" %>
        </div>

        <div id="Templates" class="tabcontent" style="border: none">
          <%= render "templates_list" %>
        </div>

        <div id="Low" class="tabcontent" style="border: none">
          <%= render "products_list" %>
        </div>
<script>
  function openList(evt, listName) {
    // Declare all variables
    var i, tabcontent, tablinks;

    // Get all elements with class="tabcontent" and hide them
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
    }

    // Get all elements with class="tablinks" and remove the class "active"
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" active", "");
    }

    // Show the current tab, and add an "active" class to the button that opened the tab
    document.getElementById(listName).style.display = "block";
    evt.currentTarget.className += " active";
  }
  document.getElementById("defaultOpen").click();
</script>

  </div>
    <% else %>
     <%= render "landing_page" %>
    <% end %>
</div>
<br>
<br>

app/views/pages/results.html.erb
<div class="container">
  <h1>Search Results:</h1>
  <div class="search-results" style="text-decoration: none">
    <% if @results.count > 0 %>
      <% @results.each do |result| %>
        <div class="notif-card2 templates">
          <h5 class="search-results"><%= link_to "#{result.searchable.name}", result.searchable, :style => 'text-decoration: none' %></h5>
          <% if result.searchable.is_a?(Product) %>
            <p>Supplier: <%= result.searchable.supplier.name %></p>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p>No results</p>
    <% end %>
  </div>
</div>

<%# <% @results.each do |result| %>
    <%# <p>Supplier: <%= link_to "#{result.searchable.name}", result.searchable_path if result.searchable == "Supplier" %>
    <%# <p>Product: <%= result.searchable.name %>
    <%# <% link_to "#{Supplier.where(products: "#{result.searchable}").name}", Supplier.where(products: "#{result.searchable}") %>
     <%# Price: $<%= result.searchable.price %>