config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'results', to: 'pages#results'
  resources :suppliers, only: [ :index, :show, :new, :create ] do
    resources :orders, only: [ :index, :show, :new, :create, :update ], type: "order"
    resources :templates, only: [ :index, :new, :create, :edit, :update ], controller: :orders, type: "template"
    resources :products, only: [ :new, :create ]
  end

  # get 'templates', to: "orders#index", type: "template"
  # resources :templates, only: %i[index new create edit update destroy], type: "template"

  resources :templates, controller: :orders, type: "template"

  resources :orders, only: [:index, :new, :show, :create, :update ], type: "order"
  resources :products, only: %i[index show update]
  resources :inventories, only: [:index, :show, :update] do
    collection do
      get :sync
    end
  end

end

app/models/supplier.rb
class Supplier < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:name]

  has_many :orders
  has_many :templates
  validates :name, :email, :address, presence: true
  validates :email, format: { with: Devise.email_regexp }

  has_many :products
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end

  def show
    @supplier = Supplier.find(params[:id])
    @orders_of_supplier = (Order.where(supplier_id: (params[:id]))).count
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to suppliers_path
    else
      render :new
    end
  end

  private

  def supplier_params
    params.require(:supplier).permit(:name, :address, :email)
  end
end

app/views/suppliers/index.html.erb
<div class="container suppliers-body">

  <h1><strong> Choose a Supplier </strong></h1> <br>

  <div class="card-suppliers">

      <% @suppliers.each do |supplier| %>
        <%= link_to supplier_path(supplier), :style=>'text-decoration: none; list-style: none' do %>
          <li class="notif-card2 mb-2 templates">
            <%= supplier.name %>
          </li>
        <% end %>
      <% end  %>
  </div>
<br>
  <div class="button-suppliers" align="center">
    <%= link_to new_supplier_path(@supplier) do %>
    <i class="fa-solid fa-circle-plus fa-2xl"></i>
    <% end %>
  </div>


</div>

app/views/suppliers/new.html.erb
<div class="container form">
  <h1>Create a new supplier</h1>
  <div class="form-inputs">
    <%= simple_form_for(@supplier) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :email %>
      <%= f.submit "Submit", class: "push-btn", :style => 'align-items: center' %>
    <% end %>
  </div>
</div>

app/views/suppliers/show.html.erb
<div class="container col-12 my-2">
  <span style="font-weight:bold; color: grey;">Supplier</span><br>
  <h1><%= @supplier.name %></h1>
  <br>
  <div class="supplier-details-container">
  <%# <div class="supplier_details"> %>
    <li><strong>Address</strong><br><%= @supplier.address %></li><br>
    <li><strong>Contact</strong><br><%= @supplier.email %> </li><br>
    <li><strong>Orders</strong><br>You have <%= @orders_of_supplier %> orders with <%= @supplier.name %>
  </div>
<br>
   <div class="row d-flex justify-content-center">
      <div class="col-6">
        <%= link_to "Create an Order", supplier_templates_path(@supplier.id), class: "push-btn-small" %>
        <%# <%= link_to "Create an Order", supplier_templates_path(@supplier.id), class: "btn-action-link btn" %>
      </div>
      <div class="col-6">
        <%= link_to "View Past Orders", supplier_orders_path(@supplier.id), class: "push-btn-small" %>
        <%# <%= link_to "View Past Orders", supplier_orders_path(@supplier.id), class: "btn-action-link btn" %>
      </div>
  </div>
</div>